import "./AddDonor.css";

const AddDonor = () => {
  return (
    <div className="card shadow">
      {/* Header */}
      <div className="card-header d-flex font-size justify-content-center align-items-center">
        <div className="header-content d-flex align-items-center">
          <i className="fa-solid fa-droplet"></i>
          <h4 className="mb-0">Add New Donor</h4>
        </div>
      </div>

      {/* Form */}
      <form className="p-4">
        {/* Donor Name */}
        <div className="mb-3">
          <label htmlFor="donorName" className="form-label">
            Donor Name
          </label>
          <input
            type="text"
            className="form-control no-border"
            id="donorName"
            name="donorName"
            placeholder="Donor Full Name"
            required
          />
        </div>

        {/* Donor ID */}
        <div className="mb-3">
          <label htmlFor="donorId" className="form-label">
            Donor ID
          </label>
          <input
            type="text"
            className="form-control no-border"
            id="donorId"
            name="donorId"
            value="Auto-generated"
            disabled
          />
          <div className="form-text">
            Donor ID will be auto-generated by the database.
          </div>
        </div>

        {/* Age & Gender */}
        <div className="mb-3 row">
          <div className="col-sm-6 col-12">
            <label htmlFor="age" className="form-label">
              Age
            </label>
            <input
              type="number"
              className="form-control no-border"
              id="age"
              name="age"
              min="1"
              required
            />
          </div>

          <div className="col-sm-6 col-12">
            <label htmlFor="gender" className="form-label">
              Gender
            </label>
            <select
              className="form-select no-border"
              id="gender"
              name="gender"
              required
            >
              <option value="" disabled selected>
                Select
              </option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
          </div>
        </div>

        {/* Phone & Email */}
        <div className="row mb-3">
          <div className="col-sm-6 col-12 mb-3 mb-sm-0">
            <label htmlFor="phone" className="form-label">
              Phone No
            </label>
            <input
              type="tel"
              className="form-control no-border"
              id="phone"
              name="phone"
              maxLength="10"
              placeholder="10-digit phone number"
              required
            />
          </div>

          <div className="col-sm-6 col-12">
            <label htmlFor="email" className="form-label">
              Email
            </label>
            <input
              type="email"
              className="form-control no-border"
              id="email"
              name="email"
              placeholder="example@email.com"
            />
          </div>
        </div>

        {/* Last Donation Date & Blood Group */}
        <div className="row mb-3">
          <div className="col-sm-6 col-12 mb-3 mb-sm-0">
            <label htmlFor="lastdonationdate" className="form-label">
              Last Donation Date
            </label>
            <input
              type="date"
              className="form-control no-border"
              id="lastdonationdate"
              name="lastdonationdate"
              required
            />
            <div className="form-text">
              Last Donation Date will be auto-generated by the database.
            </div>
          </div>

          <div className="col-sm-6 col-12">
            <label htmlFor="bloodGroup" className="form-label">
              Blood Group
            </label>
            <select
              className="form-select no-border"
              id="bloodGroup"
              name="bloodGroup"
              required
            >
              <option value="" disabled selected>
                Select
              </option>
              <option value="A+">A+</option>
              <option value="A-">A-</option>
              <option value="B+">B+</option>
              <option value="B-">B-</option>
              <option value="AB+">AB+</option>
              <option value="AB-">AB-</option>
              <option value="O+">O+</option>
              <option value="O-">O-</option>
            </select>
          </div>
        </div>

        {/* Address */}
        <div className="mb-3">
          <label htmlFor="address" className="form-label">
            Address
          </label>
          <textarea
            className="form-control no-border"
            id="address"
            name="address"
            rows="2"
            required
          ></textarea>
        </div>

        {/* Submit Button */}
        <div className="d-flex justify-content-center">
          <button type="submit" className="btn btn-theme button">
            Submit
          </button>
        </div>
      </form>
    </div>
  );
};

export default AddDonor;
